### PR TITLE
Comparing Referer with properly filled vars

### PR DESCRIPTION
**Pull request by Thelvaen**
Fixing issue https://github.com/iris-contrib/middleware/issues/64

### CODE REVIEW

**Comment by kataras** [comment]
Hello @Thelvaen I think there is no reason to `url.Parse` on every request, if host is missing on `Request.URL (*URL)` get it by `ctx.Host()`  and change the [sameOrigin](https://github.com/iris-contrib/middleware/blob/07e8bced147f7d79e278dfd67a236ee7aa4cec9e/csrf/helpers.go#L111-L11) (which is a simple function) to compare just the scheme and the host instead, e.g. sameOrigin(ctx.Request.URL.Scheme, `ctx.Host()`)

**Comment by Thelvaen** [comment]
Hello @kataras 

> Hello @Thelvaen, the problem is visible when a referer exists, right?

Correct.

> I think there is no reason to `url.Parse` on every request, if host is missing on `Request.URL (*URL)` get it by `ctx.Host()` and change the [sameOrigin](https://github.com/iris-contrib/middleware/blob/07e8bced147f7d79e278dfd67a236ee7aa4cec9e/csrf/helpers.go#L111-L11) (which is a simple function) to compare just the scheme and the host instead, e.g. sameOrigin(ctx.Request.URL.Scheme, `ctx.Host()`)

to be honnest, the sameOrigin function is a one-liner, that is only called at that specific point, below code should be enough & self explanatory, testing the scheme is in fact not needed, it has been tested earlier in the function, hence the whole thing could be simplified.

```go
func (csrf *CSRF) Filter(ctx iris.Context) bool {
// Code not shown here
			if ctx.Host() != referer.Hostname() {
				for _, trustedOrigin := range opts.TrustedOrigins {
					if referer.Host == trustedOrigin {
						valid = true
						break
					}
				}
			}
// Code not shown here too
}
```

**Comment by Thelvaen** [comment]
Note : I think we might need to check against referer.Host and not referer.Hostname, testing atm

**Comment by Thelvaen** [comment]
ok so we need to compare the ctx.Host() with referer.Host, and for some reasons, I had to use strings.Compare instead of just == or != ...

**Comment by Thelvaen** [comment]
@kataras I'm not that familiar with Github (or git for that matter) workflows, hence if I need to close this Pull Request to create a new one, just tell me :)

**Comment by kataras** [comment]
@Thelvaen the PR is OK, however `strings.Compare` and `==` are exactly the same thing, but the most correct one would be `strings.EqualFold` (search its godocs, you will learn a new thing here :))

**Comment by Thelvaen** [comment]
> @Thelvaen the PR is OK, however `strings.Compare` and `==` are exactly the same thing, but the most correct one would be `strings.EqualFold` (search its godocs, you will learn a new thing here :))

not exactly the same as == or !=, because it will return -1, 0 or 1 depending on the comparison, but for some reasons, when I tried with != or == in my test instead of strings.Compare, I had the following in the debug :

ctx.Host() = hostname.domain.tld:8090
referer.Host = hostname.domain.tld:8090
ctx.Host() == referer.Host ==> false

Maybe I could have sorted it in an other way by getting a var with ctx.Host() result before comparing?

**Comment by Thelvaen** [comment]
and yes, UTF-8 comparison is indeed better in that case.

**Comment by kataras** [comment]
`ctx.Host() == referer.Host ==> false` This fail because the `URL.Host` may be empty but its `Request.Host` is not.

**Comment by kataras** [comment]
Hello @Thelvaen,

`ctx.Host() == referer.Host ==> false` This fail because the `URL.Host` may be empty but its `Request.Host` is not. You could also use the [context.GetHost(r)](https://github.com/kataras/iris/blob/5b6802d00eaf820cb90fe2864620dfabb62ee0bc/context/context.go#L878-L884) (the `ctx.Host()` underline's function).

--------------

Also, please change:

```go
			valid := false
			if strings.EqualFold(referer.Host, ctx.Host()) {
				valid = true
			}
```

to:

```go
valid := strings.EqualFold(referer.Host, ctx.Host()) 
```

And one more note about the new `	ErrParseURL = errors.New("Can't Parse URL from context")`.

1. is not used at all, so you should remove it entirely and
2. In Go, errors text should NOT be capitalized, unless its a word like `HTTP, CRSF` and e.t.c.

**Comment by Thelvaen** [comment]
Hello @kataras,

I removed the error, and yeah I don't know why I put caps in it, as it was no longer used. I also removed the sameOrigin function, as it was no longer called.

I also changed the code according to your suggestion, I don't know why I did not saw it in the first place.
After rereading the whole block, I also simplified it a bit.

By the way, this is unrelated to this issue, but I believe we could discard the following functions :
envError, contextSave as they are one liner, and the inner they are calling are pretty self explanatory
contextGet is also pretty much a one liner, considering that the only time it's called, the error it could return is not processed

**Review by kataras — APPROVED** [review]
LGTM now! Thanks @Thelvaen

**Pull request merged**
