### PR TITLE
Follow prometheus monitoring best practices

### PR DESCRIPTION
**Pull request by thomasbarton**
Prometheus has recommended best practices.

1. Common metrics should have the same universal name.  http requests should be named with `http` prefix
- `http_requests_total`
- `http_request_duration_seconds`

2. We should use the same base units across all metrics.  For time the base unit is seconds

references
- https://prometheus.io/docs/practices/naming/
- https://www.robustperception.io/who-wants-seconds

### CODE REVIEW

**Comment by kataras** [comment]
Hello @thomasbarton , can you fix `prometheus/prometheus.go:71:45: cannot use ctx.GetStatusCode() (type int) as type string in argument to p.latency.WithLabelValues` (https://travis-ci.org/iris-contrib/middleware/jobs/406472876)?

**Comment by thomasbarton** [comment]
@kataras sorry about that - it should be fixed now

**Comment by thomasbarton** [comment]
build is green

**Comment by kataras** [comment]
Thanks @thomasbarton and sorry for my delay, you're awesome!

**Pull request merged**
